[package]
name = "terminal-projection"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
base64 = { workspace = true }
serde = { workspace = true }
terminal-domain = { path = "../terminal-domain" }
terminal-mux-domain = { path = "../terminal-mux-domain" }
unicode-width = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
