// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeScreenDelta } from "./NodeScreenDelta";
import type { NodeTopologySnapshot } from "./NodeTopologySnapshot";

export type NodeSubscriptionEvent = { "kind": "topology_snapshot" } & NodeTopologySnapshot | { "kind": "screen_delta" } & NodeScreenDelta;
