// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeScreenLineMedia } from "./NodeScreenLineMedia.js";
import type { NodeScreenLineSemanticMark } from "./NodeScreenLineSemanticMark.js";
import type { NodeScreenLineSideEffect } from "./NodeScreenLineSideEffect.js";
import type { NodeScreenLineSpan } from "./NodeScreenLineSpan.js";

export type NodeScreenLine = { text: string, spans: Array<NodeScreenLineSpan>, media?: Array<NodeScreenLineMedia>, side_effects?: Array<NodeScreenLineSideEffect>, semantic_marks?: Array<NodeScreenLineSemanticMark>, wrapped?: boolean, };
