// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeScreenTextStyle } from "./NodeScreenTextStyle.js";

export type NodeScreenLineSpan = { text: string, style: NodeScreenTextStyle, };
