// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeSplitDirection } from "./NodeSplitDirection.js";

export type NodeSplitPaneCommand = { pane_id: string, direction: NodeSplitDirection, };
