// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NodeSavedSessionCompatibilityStatus = "compatible" | "binary_skew" | "format_version_unsupported" | "protocol_major_unsupported" | "protocol_minor_ahead";
