// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeBackendCapabilities } from "./NodeBackendCapabilities.js";
import type { NodeBackendKind } from "./NodeBackendKind.js";

export type NodeBackendCapabilitiesInfo = { backend: NodeBackendKind, capabilities: NodeBackendCapabilities, };
