// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodePaneTreeNode } from "./NodePaneTreeNode";

export type NodeTabSnapshot = { tab_id: string, title: string | null, root: NodePaneTreeNode, focused_pane: string | null, };
