// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeProjectionSource } from "./NodeProjectionSource";
import type { NodeScreenSurface } from "./NodeScreenSurface";

export type NodeScreenSnapshot = { pane_id: string, sequence: bigint, rows: number, cols: number, source: NodeProjectionSource, surface: NodeScreenSurface, };
