// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeSessionRoute } from "./NodeSessionRoute.js";

export type NodeDiscoveredSession = { route: NodeSessionRoute, title: string | null, };
