// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NodeCommandHistoryEntry = { id: string, session_id: string | null, pane_id: string | null, display_text: string, last_used_at_ms: bigint, use_count: bigint, };
