// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeNewTabCommand } from "./NodeNewTabCommand.js";
import type { NodeOverrideLayoutCommand } from "./NodeOverrideLayoutCommand.js";
import type { NodeRenameTabCommand } from "./NodeRenameTabCommand.js";
import type { NodeResizePaneCommand } from "./NodeResizePaneCommand.js";
import type { NodeSendInputCommand } from "./NodeSendInputCommand.js";
import type { NodeSendPasteCommand } from "./NodeSendPasteCommand.js";
import type { NodeSplitPaneCommand } from "./NodeSplitPaneCommand.js";

export type NodeMuxCommand = { "kind": "split_pane" } & NodeSplitPaneCommand | { "kind": "close_pane", pane_id: string, } | { "kind": "focus_pane", pane_id: string, } | { "kind": "resize_pane" } & NodeResizePaneCommand | { "kind": "new_tab" } & NodeNewTabCommand | { "kind": "close_tab", tab_id: string, } | { "kind": "focus_tab", tab_id: string, } | { "kind": "rename_tab" } & NodeRenameTabCommand | { "kind": "send_input" } & NodeSendInputCommand | { "kind": "send_paste" } & NodeSendPasteCommand | { "kind": "detach" } | { "kind": "save_session" } | { "kind": "override_layout" } & NodeOverrideLayoutCommand;
