// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeSessionHealthPhase } from "./NodeSessionHealthPhase.js";
import type { NodeSessionHealthReason } from "./NodeSessionHealthReason.js";

export type NodeSessionHealthSnapshot = { session_id: string, phase: NodeSessionHealthPhase, can_attach: boolean, invalidated: boolean, reason: NodeSessionHealthReason | null, detail: string | null, };
