// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NodePaneHistoryScreenSnapshot = { id: string, pane_id: string, projection_source: string, buffer_kind: string, rows: number, cols: number, base_event_seq: bigint, high_water_event_seq: bigint, high_water_byte_seq: bigint | null, screen_json: string, parser_version: string, projection_version: string, checksum: string, created_at_ms: bigint, };
