// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeScreenLineSemanticMarkKind } from "./NodeScreenLineSemanticMarkKind.js";

export type NodeScreenLineSemanticMark = { kind: NodeScreenLineSemanticMarkKind, col?: number, exit_code?: number, };
