// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeScreenCursor } from "./NodeScreenCursor";
import type { NodeScreenLine } from "./NodeScreenLine";

export type NodeScreenSurface = { title: string | null, cursor: NodeScreenCursor | null, lines: Array<NodeScreenLine>, };
