// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NodeSessionHealthReason = "backend_degraded" | "subscription_source_closed" | "session_not_found" | "backend_transport_lost" | "backend_internal_fault";
