// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeScreenSnapshot } from "./NodeScreenSnapshot";
import type { NodeSessionSummary } from "./NodeSessionSummary";
import type { NodeTopologySnapshot } from "./NodeTopologySnapshot";

export type NodeAttachedSession = { session: NodeSessionSummary, topology: NodeTopologySnapshot, focused_screen: NodeScreenSnapshot | null, };
