// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NodeScreenLineSideEffectKind = "clipboard_write" | "clipboard_read" | "desktop_notification";
