// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NodeSavedSessionManifest = { format_version: number, binary_version: string, protocol_major: number, protocol_minor: number, };
