// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeScreenCursorShape } from "./NodeScreenCursorShape.js";

export type NodeScreenCursor = { row: number, col: number, shape?: NodeScreenCursorShape, blinking?: boolean, };
