// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeBackendKind } from "./NodeBackendKind";
import type { NodeDaemonCapabilities } from "./NodeDaemonCapabilities";
import type { NodeDaemonPhase } from "./NodeDaemonPhase";
import type { NodeProtocolVersion } from "./NodeProtocolVersion";

export type NodeHandshake = { protocol_version: NodeProtocolVersion, binary_version: string, daemon_phase: NodeDaemonPhase, capabilities: NodeDaemonCapabilities, available_backends: Array<NodeBackendKind>, session_scope: string, };
