// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeBackendKind } from "./NodeBackendKind";
import type { NodeExternalSessionRef } from "./NodeExternalSessionRef";
import type { NodeRouteAuthority } from "./NodeRouteAuthority";

export type NodeSessionRoute = { backend: NodeBackendKind, authority: NodeRouteAuthority, external: NodeExternalSessionRef | null, };
