// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeShellLaunchSpec } from "./NodeShellLaunchSpec";

export type NodeCreateSessionRequest = { title: string | null, launch: NodeShellLaunchSpec | null, };
