// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeBackendKind } from "./NodeBackendKind";
import type { NodeTabSnapshot } from "./NodeTabSnapshot";

export type NodeTopologySnapshot = { session_id: string, backend_kind: NodeBackendKind, tabs: Array<NodeTabSnapshot>, focused_tab: string | null, };
