// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeHandshakeAssessmentStatus } from "./NodeHandshakeAssessmentStatus";
import type { NodeProtocolCompatibility } from "./NodeProtocolCompatibility";

export type NodeHandshakeAssessment = { can_use: boolean, protocol: NodeProtocolCompatibility, status: NodeHandshakeAssessmentStatus, };
