// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeHandshake } from "./NodeHandshake";
import type { NodeHandshakeAssessment } from "./NodeHandshakeAssessment";

export type NodeHandshakeInfo = { handshake: NodeHandshake, assessment: NodeHandshakeAssessment, };
