// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeScreenLine } from "./NodeScreenLine";

export type NodeScreenLinePatch = { row: number, line: NodeScreenLine, };
