// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeScreenCursor } from "./NodeScreenCursor";
import type { NodeScreenLinePatch } from "./NodeScreenLinePatch";

export type NodeScreenPatch = { title_changed: boolean, title: string | null, cursor_changed: boolean, cursor: NodeScreenCursor | null, line_updates: Array<NodeScreenLinePatch>, };
