// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeSavedSessionCompatibility } from "./NodeSavedSessionCompatibility.js";
import type { NodeSavedSessionManifest } from "./NodeSavedSessionManifest.js";
import type { NodeSavedSessionRestoreSemantics } from "./NodeSavedSessionRestoreSemantics.js";
import type { NodeSessionSummary } from "./NodeSessionSummary.js";

export type NodeRestoredSession = { saved_session_id: string, manifest: NodeSavedSessionManifest, compatibility: NodeSavedSessionCompatibility, session: NodeSessionSummary, restore_semantics: NodeSavedSessionRestoreSemantics, };
