// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeSavedSessionCompatibility } from "./NodeSavedSessionCompatibility";
import type { NodeSavedSessionManifest } from "./NodeSavedSessionManifest";
import type { NodeSavedSessionRestoreSemantics } from "./NodeSavedSessionRestoreSemantics";
import type { NodeSessionSummary } from "./NodeSessionSummary";

export type NodeRestoredSession = { saved_session_id: string, manifest: NodeSavedSessionManifest, compatibility: NodeSavedSessionCompatibility, session: NodeSessionSummary, restore_semantics: NodeSavedSessionRestoreSemantics, };
