// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeSavedSessionCompatibilityStatus } from "./NodeSavedSessionCompatibilityStatus.js";

export type NodeSavedSessionCompatibility = { can_restore: boolean, status: NodeSavedSessionCompatibilityStatus, };
