// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NodeRestoreGuaranteeLevel = "rich_history" | "basic_history" | "visual_restore_only" | "history_degraded";
