// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeScreenLineSideEffectDisposition } from "./NodeScreenLineSideEffectDisposition.js";
import type { NodeScreenLineSideEffectKind } from "./NodeScreenLineSideEffectKind.js";
import type { NodeScreenLineSideEffectTarget } from "./NodeScreenLineSideEffectTarget.js";

export type NodeScreenLineSideEffect = { kind: NodeScreenLineSideEffectKind, disposition: NodeScreenLineSideEffectDisposition, target?: NodeScreenLineSideEffectTarget, message?: string, };
