// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeSavedSessionCompatibility } from "./NodeSavedSessionCompatibility.js";
import type { NodeSavedSessionManifest } from "./NodeSavedSessionManifest.js";
import type { NodeSavedSessionRestoreSemantics } from "./NodeSavedSessionRestoreSemantics.js";
import type { NodeScreenSnapshot } from "./NodeScreenSnapshot.js";
import type { NodeSessionRoute } from "./NodeSessionRoute.js";
import type { NodeShellLaunchSpec } from "./NodeShellLaunchSpec.js";
import type { NodeTopologySnapshot } from "./NodeTopologySnapshot.js";

export type NodeSavedSessionRecord = { session_id: string, route: NodeSessionRoute, title: string | null, launch: NodeShellLaunchSpec | null, manifest: NodeSavedSessionManifest, compatibility: NodeSavedSessionCompatibility, topology: NodeTopologySnapshot, screens: Array<NodeScreenSnapshot>, saved_at_ms: bigint, restore_semantics: NodeSavedSessionRestoreSemantics, };
