// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeProtocolCompatibilityStatus } from "./NodeProtocolCompatibilityStatus.js";

export type NodeProtocolCompatibility = { can_connect: boolean, status: NodeProtocolCompatibilityStatus, };
