// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeSavedSessionCompatibility } from "./NodeSavedSessionCompatibility";
import type { NodeSavedSessionManifest } from "./NodeSavedSessionManifest";
import type { NodeSavedSessionRestoreSemantics } from "./NodeSavedSessionRestoreSemantics";
import type { NodeSessionRoute } from "./NodeSessionRoute";

export type NodeSavedSessionSummary = { session_id: string, route: NodeSessionRoute, title: string | null, saved_at_ms: bigint, manifest: NodeSavedSessionManifest, compatibility: NodeSavedSessionCompatibility, has_launch: boolean, tab_count: number, pane_count: number, restore_semantics: NodeSavedSessionRestoreSemantics, };
