// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeScreenCursor } from "./NodeScreenCursor.js";
import type { NodeScreenLinePatch } from "./NodeScreenLinePatch.js";
import type { NodeScreenProgress } from "./NodeScreenProgress.js";
import type { NodeScreenSurfacePalette } from "./NodeScreenSurfacePalette.js";

export type NodeScreenPatch = { title_changed: boolean, title: string | null, working_directory_uri_changed: boolean, working_directory_uri: string | null, user_variables_changed: boolean, user_variables: { [key in string]: string } | null, cursor_changed: boolean, cursor: NodeScreenCursor | null, palette_changed: boolean, palette: NodeScreenSurfacePalette | null, bell_count_changed: boolean, bell_count: bigint | null, progress_changed: boolean, progress: NodeScreenProgress | null, line_updates: Array<NodeScreenLinePatch>, };
