export {
  TerminalCommandDock,
  TerminalPaneTree,
  TerminalSavedSessions,
  TerminalScreen,
  TerminalSessionList,
  TerminalStatusBar,
  TerminalToolbar,
  TerminalWorkspace,
} from "./components/terminal-workspace.js";
export { useWorkspaceSnapshot } from "./hooks/use-workspace-snapshot.js";
export {
  TERMINAL_COMMAND_QUICK_COMMAND_LIMIT,
  TERMINAL_PANE_MAX_COLS,
  TERMINAL_PANE_MAX_ROWS,
  TERMINAL_PANE_MIN_COLS,
  TERMINAL_PANE_MIN_ROWS,
  TERMINAL_SAVED_SESSIONS_DEFAULT_VISIBLE_COUNT,
  canRunTerminalTopologyCommand,
  compactTerminalId,
  countPaneTreeLeaves,
  findRestorableSavedSession,
  hasSavedSession,
  defaultTerminalCommandQuickCommands,
  resolveActiveBackendCapabilities,
  resolvePaneResizeCommand,
  resolveTerminalCommandDockControlState,
  resolveTerminalEntityIdLabel,
  resolveTerminalCommandInputStatus,
  resolveTerminalCommandQuickCommands,
  resolveTerminalSavedSessionsControlState,
  resolveTerminalScreenControlState,
  resolveTerminalScreenInputStatus,
  resolveTerminalTopologyControlState,
  resolveTerminalTopologyStatus,
  resolveWorkspaceCapability,
} from "@terminal-platform/workspace-elements";

export type {
  TerminalCommandDockCapabilityStatus,
  TerminalCommandDockControlState,
  TerminalCommandInputStatus,
  TerminalCommandQuickCommand,
  TerminalEntityIdLabel,
  TerminalEntityIdLabelOptions,
  TerminalPaneResizeDelta,
  TerminalPaneSize,
  TerminalSavedSessionItemControlState,
  TerminalSavedSessionPendingAction,
  TerminalSavedSessionRestoreSemanticsNote,
  TerminalSavedSessionRestoreSemanticsTone,
  TerminalSavedSessionRestoreStatus,
  TerminalSavedSessionsBulkAction,
  TerminalSavedSessionsControlOptions,
  TerminalSavedSessionsControlState,
  TerminalScreenControlState,
  TerminalScreenInputActivity,
  TerminalScreenInputStatus,
  TerminalScreenInputTone,
  TerminalTopologyControlState,
  TerminalTopologyStatus,
  TerminalWorkspaceCapabilityState,
  TerminalWorkspaceCapabilityStatus,
} from "@terminal-platform/workspace-elements";
